#!name=My Rules
#!desc=My Own Rules
[General]
#dns-server = 1.1.1.1

[Rule]
DOMAIN-SUFFIX,itunes.apple.com,PROXY
DOMAIN-SUFFIX,tv.apple.com,PROXY
DOMAIN-SUFFIX,bookkeeper.itunes.apple.com,PROXY
DOMAIN-SUFFIX,podcasts.apple.com,PROXY
DOMAIN-SUFFIX,books.apple.com,PROXY
DOMAIN-SUFFIX,mzstatic.com,PROXY
DOMAIN-SUFFIX,outlook.live.com,PROXY